spring.application.name=account-service

server.servlet.context-path=/account/api/v1
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5400}/${DB_NAME:account_db}
spring.datasource.username=${DB_USERNAME:account_user}
spring.datasource.password=${DB_PASSWORD:account_password}

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.validation-timeout=3000